services:
  - type: web
    name: ships-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        value: mongodb+srv://nndminh03:psrMirsKkv19Yia6@ships-cluster.guijyap.mongodb.net/ships_db
      - key: JWT_SECRET
        value: your_super_secret_jwt_key_2024
      - key: CORS_ORIGIN
        value: https://ships-customermoi.onrender.com
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_APP
        value: calc_distance_api.py
      - key: FLASK_ENV
        value: production 